// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CheckData, CheckErrors, CheckResponses, CliLoginData, CliLoginErrors, CliLoginResponses, CountImagesData, CountImagesErrors, CountImagesResponses, DeleteImageData, DeleteImageErrors, DeleteImageResponses, DownloadData, DownloadErrors, DownloadResponses, GetImageData, GetImageErrors, GetImageResponses, ListImagesData, ListImagesErrors, ListImagesResponses, LoginData, LoginErrors, LoginResponses, RenameImageData, RenameImageErrors, RenameImageResponses, RestoreImageData, RestoreImageErrors, RestoreImageResponses, UploadData, UploadErrors, UploadResponses, ViewData, ViewErrors, ViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * GET /api/admin/images
 */
export const listImages = <ThrowOnError extends boolean = false>(options?: Options<ListImagesData, ThrowOnError>) => (options?.client ?? client).get<ListImagesResponses, ListImagesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/admin/images',
    ...options
});

/**
 * GET /api/admin/images/count
 */
export const countImages = <ThrowOnError extends boolean = false>(options?: Options<CountImagesData, ThrowOnError>) => (options?.client ?? client).get<CountImagesResponses, CountImagesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/admin/images/count',
    ...options
});

/**
 * GET /api/admin/images/:id
 */
export const getImage = <ThrowOnError extends boolean = false>(options: Options<GetImageData, ThrowOnError>) => (options.client ?? client).get<GetImageResponses, GetImageErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/admin/images/{id}',
    ...options
});

/**
 * POST /api/admin/images/:id/delete
 */
export const deleteImage = <ThrowOnError extends boolean = false>(options: Options<DeleteImageData, ThrowOnError>) => (options.client ?? client).post<DeleteImageResponses, DeleteImageErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/admin/images/{id}/delete',
    ...options
});

/**
 * POST /api/admin/images/:id/rename
 */
export const renameImage = <ThrowOnError extends boolean = false>(options: Options<RenameImageData, ThrowOnError>) => (options.client ?? client).post<RenameImageResponses, RenameImageErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/admin/images/{id}/rename',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * POST /api/admin/images/:id/restore
 */
export const restoreImage = <ThrowOnError extends boolean = false>(options: Options<RestoreImageData, ThrowOnError>) => (options.client ?? client).post<RestoreImageResponses, RestoreImageErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/admin/images/{id}/restore',
    ...options
});

/**
 * GET /api/auth/check
 * Returns 200 if the user is authenticated.
 */
export const check = <ThrowOnError extends boolean = false>(options?: Options<CheckData, ThrowOnError>) => (options?.client ?? client).get<CheckResponses, CheckErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/auth/check',
    ...options
});

/**
 * GET /api/auth/cli?token=<one-time-token>
 * Validates the one-time CLI token and sets JWT cookie.
 */
export const cliLogin = <ThrowOnError extends boolean = false>(options: Options<CliLoginData, ThrowOnError>) => (options.client ?? client).get<CliLoginResponses, CliLoginErrors, ThrowOnError>({ url: '/api/auth/cli', ...options });

/**
 * POST /api/auth/login
 * Body: { "token": "<AUTH_TOKEN from .env>" }
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * POST /api/upload
 */
export const upload = <ThrowOnError extends boolean = false>(options: Options<UploadData, ThrowOnError>) => (options.client ?? client).post<UploadResponses, UploadErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{
            in: 'cookie',
            name: 'ibed_token',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * GET /d/{*path}
 */
export const download = <ThrowOnError extends boolean = false>(options: Options<DownloadData, ThrowOnError>) => (options.client ?? client).get<DownloadResponses, DownloadErrors, ThrowOnError>({ url: '/d/{path}', ...options });

/**
 * GET /v/{*path}
 */
export const view = <ThrowOnError extends boolean = false>(options: Options<ViewData, ThrowOnError>) => (options.client ?? client).get<ViewResponses, ViewErrors, ThrowOnError>({ url: '/v/{path}', ...options });
