// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuthCheckResponse = {
    ok: boolean;
    user: string;
};

export type AuthSuccessResponse = {
    ok: boolean;
};

export type CliLoginQuery = {
    token: string;
};

/**
 * How clients access images stored on an S3 endpoint.
 */
export type DirectMode = 'proxy' | 'presigned' | 'public';

export type ImageCountResponse = {
    active: number;
    in_trash: number;
};

export type ImageDetailResponse = {
    direct_url?: string | null;
    image: ImageModel;
    /**
     * Whether the image file is available on at least one active storage node.
     * Only populated in admin API responses; null means not checked.
     */
    storage_available?: boolean | null;
    view_url: string;
};

export type ImageListItem = {
    created_at: string;
    direct_url?: string | null;
    display_name: string;
    extension: string;
    file_name: string;
    hash: string;
    height: number;
    id: number;
    is_deleted: boolean;
    mime_type: string;
    size: number;
    /**
     * Whether the image file is available on at least one active storage node.
     * Only populated in admin API responses; null means not checked.
     */
    storage_available?: boolean | null;
    updated_at: string;
    user_id?: string | null;
    view_url: string;
    width: number;
};

export type ImageListQuery = {
    /**
     * Start date (YYYY-MM-DD)
     */
    date_from?: string | null;
    /**
     * End date (YYYY-MM-DD)
     */
    date_to?: string | null;
    /**
     * Filter by deletion status; defaults to non-deleted images when omitted
     */
    deleted?: boolean | null;
    /**
     * Fuzzy search by display_name
     */
    name?: string | null;
    /**
     * Page number, starting from 1
     */
    page?: number;
    /**
     * Items per page
     */
    per_page?: number;
};

export type ImageListResponse = {
    items: Array<ImageListItem>;
    page: number;
    per_page: number;
    total: number;
};

export type ImageModel = {
    created_at: string;
    display_name: string;
    extension: string;
    file_name: string;
    hash: string;
    height: number;
    id: number;
    is_deleted: boolean;
    mime_type: string;
    size: number;
    updated_at: string;
    user_id?: string | null;
    width: number;
};

export type LoginRequest = {
    token: string;
};

export type OkResponse = {
    ok: boolean;
};

export type RenameRequest = {
    display_name: string;
};

/**
 * Response returned by GET /api/admin/storage/endpoints —
 * merges live in-memory state with config-immutable fields.
 */
export type StorageEndpointResponse = {
    capacity_bytes: number;
    description: string;
    /**
     * How clients access images: "proxy", "presigned", or "public".
     */
    direct_mode: DirectMode;
    /**
     * Backend type from config: "Local" or "S3".
     */
    endpoint_type: string;
    name: string;
    priority: number;
    status: string;
    used_size: number;
};

/**
 * Only `status` and `description` are mutable via the API.
 * `priority` and `capacity_bytes` are config-immutable.
 */
export type UpdateEndpointRequest = {
    description?: string | null;
    status?: string | null;
};

export type UploadRequest = {
    /**
     * Image file to upload
     */
    file: Blob | File;
    /**
     * Comma-separated list of metadata fields to keep (e.g. "camera,time").
     * Overrides the server-side `keep_metadata_fields` config for this upload.
     */
    keep_metadata_fields?: string | null;
};

export type UploadResponse = {
    direct_url?: string | null;
    file_name: string;
    hash: string;
    height: number;
    id: number;
    mime_type: string;
    size: number;
    url: string;
    width: number;
};

export type ListImagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number, starting from 1
         */
        page?: number;
        /**
         * Items per page
         */
        per_page?: number;
        /**
         * Fuzzy search by display_name
         */
        name?: string | null;
        /**
         * Start date (YYYY-MM-DD)
         */
        date_from?: string | null;
        /**
         * End date (YYYY-MM-DD)
         */
        date_to?: string | null;
        /**
         * Filter by deletion status; defaults to non-deleted images when omitted
         */
        deleted?: boolean | null;
    };
    url: '/api/admin/images';
};

export type ListImagesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListImagesResponses = {
    /**
     * Paginated image list
     */
    200: ImageListResponse;
};

export type ListImagesResponse = ListImagesResponses[keyof ListImagesResponses];

export type CountImagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/images/count';
};

export type CountImagesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CountImagesResponses = {
    /**
     * Image counts grouped by deletion status
     */
    200: ImageCountResponse;
};

export type CountImagesResponse = CountImagesResponses[keyof CountImagesResponses];

export type EmptyTrashData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/images/trash/empty';
};

export type EmptyTrashErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type EmptyTrashResponses = {
    /**
     * Trash emptied
     */
    200: OkResponse;
};

export type EmptyTrashResponse = EmptyTrashResponses[keyof EmptyTrashResponses];

export type GetImageData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/images/{id}';
};

export type GetImageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type GetImageResponses = {
    /**
     * Image detail
     */
    200: ImageDetailResponse;
};

export type GetImageResponse = GetImageResponses[keyof GetImageResponses];

export type DeleteImageData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/images/{id}/delete';
};

export type DeleteImageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type DeleteImageResponses = {
    /**
     * Soft deleted
     */
    200: OkResponse;
};

export type DeleteImageResponse = DeleteImageResponses[keyof DeleteImageResponses];

export type PermanentDeleteImageData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/images/{id}/permanent-delete';
};

export type PermanentDeleteImageErrors = {
    /**
     * Image not in trash
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type PermanentDeleteImageResponses = {
    /**
     * Permanently deleted
     */
    200: OkResponse;
};

export type PermanentDeleteImageResponse = PermanentDeleteImageResponses[keyof PermanentDeleteImageResponses];

export type RenameImageData = {
    body: RenameRequest;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/images/{id}/rename';
};

export type RenameImageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type RenameImageResponses = {
    /**
     * Renamed
     */
    200: OkResponse;
};

export type RenameImageResponse = RenameImageResponses[keyof RenameImageResponses];

export type RestoreImageData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/images/{id}/restore';
};

export type RestoreImageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type RestoreImageResponses = {
    /**
     * Restored
     */
    200: OkResponse;
};

export type RestoreImageResponse = RestoreImageResponses[keyof RestoreImageResponses];

export type ListStorageEndpointsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/storage/endpoints';
};

export type ListStorageEndpointsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListStorageEndpointsResponses = {
    /**
     * List of storage endpoints
     */
    200: Array<StorageEndpointResponse>;
};

export type ListStorageEndpointsResponse = ListStorageEndpointsResponses[keyof ListStorageEndpointsResponses];

export type UpdateStorageEndpointData = {
    body: UpdateEndpointRequest;
    path: {
        /**
         * Endpoint name
         */
        name: string;
    };
    query?: never;
    url: '/api/admin/storage/endpoints/{name}/update';
};

export type UpdateStorageEndpointErrors = {
    /**
     * Cannot change priority or capacity via API
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type UpdateStorageEndpointResponses = {
    /**
     * Updated
     */
    200: OkResponse;
};

export type UpdateStorageEndpointResponse = UpdateStorageEndpointResponses[keyof UpdateStorageEndpointResponses];

export type CheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/check';
};

export type CheckErrors = {
    /**
     * Not authenticated
     */
    401: unknown;
};

export type CheckResponses = {
    /**
     * Authenticated
     */
    200: AuthCheckResponse;
};

export type CheckResponse = CheckResponses[keyof CheckResponses];

export type CliLoginData = {
    body?: never;
    path?: never;
    query: {
        /**
         * One-time CLI token
         */
        token: string;
    };
    url: '/api/auth/cli';
};

export type CliLoginErrors = {
    /**
     * Invalid or expired token
     */
    401: unknown;
};

export type CliLoginResponses = {
    /**
     * Login successful, JWT cookie set
     */
    200: AuthSuccessResponse;
};

export type CliLoginResponse = CliLoginResponses[keyof CliLoginResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid token
     */
    401: unknown;
};

export type LoginResponses = {
    /**
     * Login successful, JWT cookie set
     */
    200: AuthSuccessResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type UploadData = {
    body: UploadRequest;
    path?: never;
    query?: never;
    url: '/api/upload';
};

export type UploadErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type UploadResponses = {
    /**
     * Upload successful
     */
    200: UploadResponse;
};

export type UploadResponse2 = UploadResponses[keyof UploadResponses];

export type DownloadData = {
    body?: never;
    path: {
        /**
         * Image path
         */
        path: string;
    };
    query?: never;
    url: '/d/{path}';
};

export type DownloadErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type DownloadResponses = {
    /**
     * Original image download
     */
    200: unknown;
};

export type ViewData = {
    body?: never;
    path: {
        /**
         * Image path
         */
        path: string;
    };
    query?: never;
    url: '/v/{path}';
};

export type ViewErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type ViewResponses = {
    /**
     * Processed image
     */
    200: unknown;
};
